#!/usr/bin/env python3
"""
PHASE 11 RE-TEST: AI Assistant DIVA action generation + execution
Tests the parser robustness fix with REAL LLM calls (3-10s each).
Fresh user: divafix@divarc.fr
"""
import requests
import time
import json
import sys

BASE_URL = "https://divarc-hub.preview.emergentagent.com/api"

def test_phase11_retest():
    print("=" * 80)
    print("PHASE 11 RE-TEST: AI Assistant DIVA (Claude Sonnet 4.5)")
    print("Testing action generation + execution with parser robustness fix")
    print("=" * 80)
    
    # ========== AUTH FLOW: Create fresh user divafix@divarc.fr ==========
    print("\n[AUTH] Creating fresh user divafix@divarc.fr via OTP flow...")
    email = "divafix@divarc.fr"
    
    # Step 1: Send OTP
    try:
        r = requests.post(f"{BASE_URL}/auth/otp/send", json={"email": email}, timeout=10)
        print(f"POST /auth/otp/send -> {r.status_code}")
        if r.status_code != 200:
            print(f"❌ FAIL: Expected 200, got {r.status_code}: {r.text}")
            return False
        data = r.json()
        if not data.get("ok"):
            print(f"❌ FAIL: Expected ok:true, got {data}")
            return False
        preview_code = data.get("previewCode")
        is_new = data.get("isNew")
        print(f"✅ OTP sent. isNew={is_new}, previewCode={preview_code}")
    except Exception as e:
        print(f"❌ FAIL: OTP send error: {e}")
        return False
    
    # Step 2: Verify OTP
    try:
        r = requests.post(f"{BASE_URL}/auth/otp/verify", json={"email": email, "code": preview_code}, timeout=10)
        print(f"POST /auth/otp/verify -> {r.status_code}")
        if r.status_code != 200:
            print(f"❌ FAIL: Expected 200, got {r.status_code}: {r.text}")
            return False
        data = r.json()
        token = data.get("token")
        user = data.get("user")
        if not token or not user:
            print(f"❌ FAIL: Expected token and user, got {data}")
            return False
        print(f"✅ Auth successful. User: {user.get('handle')} ({user.get('name')})")
        print(f"   Token: {token[:20]}...")
    except Exception as e:
        print(f"❌ FAIL: OTP verify error: {e}")
        return False
    
    headers = {"Authorization": f"Bearer {token}", "Content-Type": "application/json"}
    
    # Get initial wallet balance
    try:
        r = requests.get(f"{BASE_URL}/wallet", headers=headers, timeout=10)
        if r.status_code != 200:
            print(f"❌ FAIL: GET /wallet returned {r.status_code}")
            return False
        wallet = r.json()
        initial_balance = wallet.get("balanceCents", 0)
        print(f"✅ Initial wallet balance: {initial_balance} cents ({initial_balance/100:.2f} €)")
    except Exception as e:
        print(f"❌ FAIL: Wallet fetch error: {e}")
        return False
    
    # ========== TEST MESSAGES WITH REAL LLM CALLS ==========
    session_id = None  # Will be generated by first call, then reused
    
    test_cases = [
        {
            "name": "TEST 1: Send Money",
            "message": "Envoie 20 euros à Marie",
            "expected_type": "send_money",
            "expected_payload": {
                "toName": "Marie",
                "amountCents": 2000
            },
            "verify_execution": lambda result, before_balance, after_balance: (
                result.get("kind") == "send_money" and
                result.get("amountCents") == 2000 and
                "Marie" in result.get("to", "") and
                after_balance == before_balance - 2000
            ),
            "execution_checks": [
                ("Wallet decreased by 2000c", lambda r, b, a: a == b - 2000),
                ("Result kind is send_money", lambda r, b, a: r.get("kind") == "send_money"),
                ("P2P transaction created", lambda r, b, a: True)  # Will check separately
            ]
        },
        {
            "name": "TEST 2: Create Listing",
            "message": "Je veux vendre mon vélo pour 150 euros à Lyon",
            "expected_type": "create_listing",
            "expected_payload": {
                "title": "vélo",  # Should contain vélo
                "priceCents": 15000,
                "city": "Lyon"
            },
            "verify_execution": lambda result, before_balance, after_balance: (
                result.get("kind") == "create_listing" and
                result.get("listingId") is not None and
                after_balance == before_balance  # No wallet change for listing creation
            ),
            "execution_checks": [
                ("Result kind is create_listing", lambda r, b, a: r.get("kind") == "create_listing"),
                ("Listing ID present", lambda r, b, a: r.get("listingId") is not None),
                ("No wallet change", lambda r, b, a: a == b)
            ]
        },
        {
            "name": "TEST 3: Launch Ad Campaign",
            "message": "Lance une campagne de notoriété avec 50 euros de budget",
            "expected_type": "launch_ad",
            "expected_payload": {
                "budgetCents": 5000,
                "objective": "awareness"
            },
            "verify_execution": lambda result, before_balance, after_balance: (
                result.get("kind") == "launch_ad" and
                result.get("campaignId") is not None and
                after_balance == before_balance - 5000
            ),
            "execution_checks": [
                ("Wallet decreased by 5000c", lambda r, b, a: a == b - 5000),
                ("Result kind is launch_ad", lambda r, b, a: r.get("kind") == "launch_ad"),
                ("Campaign ID present", lambda r, b, a: r.get("campaignId") is not None)
            ]
        },
        {
            "name": "TEST 4: Navigate",
            "message": "Ouvre mon wallet",
            "expected_type": "navigate",
            "expected_payload": {
                "tab": "wallet"
            },
            "verify_execution": lambda result, before_balance, after_balance: (
                result.get("kind") == "navigate" and
                result.get("tab") == "wallet" and
                after_balance == before_balance  # No wallet change
            ),
            "execution_checks": [
                ("Result kind is navigate", lambda r, b, a: r.get("kind") == "navigate"),
                ("Tab is wallet", lambda r, b, a: r.get("tab") == "wallet"),
                ("No wallet change", lambda r, b, a: a == b)
            ]
        }
    ]
    
    all_passed = True
    current_balance = initial_balance
    
    for test_case in test_cases:
        print(f"\n{'=' * 80}")
        print(f"{test_case['name']}")
        print(f"Message: \"{test_case['message']}\"")
        print(f"Expected action type: {test_case['expected_type']}")
        print(f"{'=' * 80}")
        
        action_generated = False
        action_data = None
        max_retries = 2
        
        for attempt in range(max_retries + 1):
            if attempt > 0:
                print(f"\n⚠️  Retry attempt {attempt}/{max_retries} (LLM variability)...")
            
            # POST /ai/chat with REAL LLM call (be patient)
            print(f"\n[CHAT] Sending message to AI (LLM call, may take 3-10s)...")
            start_time = time.time()
            try:
                payload = {"text": test_case["message"]}
                if session_id:
                    payload["sessionId"] = session_id
                
                r = requests.post(f"{BASE_URL}/ai/chat", json=payload, headers=headers, timeout=30)
                elapsed = time.time() - start_time
                print(f"POST /ai/chat -> {r.status_code} (took {elapsed:.1f}s)")
                
                if r.status_code != 200:
                    print(f"❌ FAIL: Expected 200, got {r.status_code}: {r.text}")
                    all_passed = False
                    break
                
                data = r.json()
                if not session_id:
                    session_id = data.get("sessionId")
                    print(f"✅ Session ID: {session_id}")
                
                message = data.get("message", {})
                assistant_message = message.get("content", "")
                actions = message.get("actions", [])
                
                print(f"✅ Assistant response ({len(assistant_message)} chars): \"{assistant_message[:100]}...\"")
                print(f"   Actions returned: {len(actions)}")
                
                if len(actions) == 0:
                    print(f"⚠️  WARNING: No actions generated (LLM variability)")
                    if attempt < max_retries:
                        continue
                    else:
                        print(f"❌ FAIL: No actions generated after {max_retries + 1} attempts")
                        all_passed = False
                        break
                
                action = actions[0]
                action_data = action
                print(f"\n[ACTION] Generated action:")
                print(f"   ID: {action.get('id')}")
                print(f"   Type: {action.get('type')}")
                print(f"   Title: {action.get('title')}")
                print(f"   Payload: {json.dumps(action.get('payload', {}), ensure_ascii=False)}")
                print(f"   Risk: {action.get('risk')}")
                
                # Verify action type
                if action.get("type") != test_case["expected_type"]:
                    print(f"⚠️  WARNING: Expected type '{test_case['expected_type']}', got '{action.get('type')}'")
                    if attempt < max_retries:
                        continue
                    else:
                        print(f"❌ FAIL: Wrong action type after {max_retries + 1} attempts")
                        all_passed = False
                        break
                
                # Verify payload fields
                payload_obj = action.get("payload", {})
                expected_payload = test_case["expected_payload"]
                payload_valid = True
                
                for key, expected_value in expected_payload.items():
                    actual_value = payload_obj.get(key)
                    if key == "title" and isinstance(expected_value, str):
                        # For title, check if it contains the expected substring (case-insensitive)
                        if actual_value and expected_value.lower() in actual_value.lower():
                            print(f"   ✅ Payload.{key}: \"{actual_value}\" (contains \"{expected_value}\")")
                        else:
                            print(f"   ⚠️  Payload.{key}: \"{actual_value}\" (expected to contain \"{expected_value}\")")
                            payload_valid = False
                    elif actual_value == expected_value:
                        print(f"   ✅ Payload.{key}: {actual_value}")
                    else:
                        print(f"   ⚠️  Payload.{key}: {actual_value} (expected {expected_value})")
                        payload_valid = False
                
                if not payload_valid:
                    if attempt < max_retries:
                        continue
                    else:
                        print(f"❌ FAIL: Payload validation failed after {max_retries + 1} attempts")
                        all_passed = False
                        break
                
                action_generated = True
                break
                
            except Exception as e:
                print(f"❌ FAIL: Chat error: {e}")
                all_passed = False
                break
        
        if not action_generated or not action_data:
            continue
        
        # ========== EXECUTE ACTION ==========
        print(f"\n[EXECUTE] Executing action {action_data.get('id')}...")
        
        # Get wallet balance before execution
        try:
            r = requests.get(f"{BASE_URL}/wallet", headers=headers, timeout=10)
            if r.status_code != 200:
                print(f"❌ FAIL: GET /wallet returned {r.status_code}")
                all_passed = False
                continue
            before_balance = r.json().get("balanceCents", 0)
            print(f"   Wallet before: {before_balance} cents ({before_balance/100:.2f} €)")
        except Exception as e:
            print(f"❌ FAIL: Wallet fetch error: {e}")
            all_passed = False
            continue
        
        # Execute action
        try:
            r = requests.post(
                f"{BASE_URL}/ai/actions/{action_data.get('id')}/execute",
                json={"sessionId": session_id},
                headers=headers,
                timeout=15
            )
            print(f"POST /ai/actions/{action_data.get('id')}/execute -> {r.status_code}")
            
            if r.status_code != 200:
                print(f"❌ FAIL: Expected 200, got {r.status_code}: {r.text}")
                all_passed = False
                continue
            
            exec_data = r.json()
            result = exec_data.get("result", {})
            print(f"✅ Execution result: {json.dumps(result, ensure_ascii=False)}")
            
        except Exception as e:
            print(f"❌ FAIL: Execute error: {e}")
            all_passed = False
            continue
        
        # Get wallet balance after execution
        try:
            r = requests.get(f"{BASE_URL}/wallet", headers=headers, timeout=10)
            if r.status_code != 200:
                print(f"❌ FAIL: GET /wallet returned {r.status_code}")
                all_passed = False
                continue
            after_balance = r.json().get("balanceCents", 0)
            print(f"   Wallet after: {after_balance} cents ({after_balance/100:.2f} €)")
            print(f"   Change: {after_balance - before_balance} cents")
        except Exception as e:
            print(f"❌ FAIL: Wallet fetch error: {e}")
            all_passed = False
            continue
        
        # Verify execution
        print(f"\n[VERIFY] Checking execution results...")
        for check_name, check_fn in test_case["execution_checks"]:
            try:
                if check_fn(result, before_balance, after_balance):
                    print(f"   ✅ {check_name}")
                else:
                    print(f"   ❌ {check_name}")
                    all_passed = False
            except Exception as e:
                print(f"   ❌ {check_name}: {e}")
                all_passed = False
        
        # Additional verification for send_money: check transaction
        if test_case["expected_type"] == "send_money":
            try:
                r = requests.get(f"{BASE_URL}/transactions", headers=headers, timeout=10)
                if r.status_code == 200:
                    txs = r.json()
                    if len(txs) > 0:
                        latest_tx = txs[0]
                        if "via DIVA" in latest_tx.get("label", ""):
                            print(f"   ✅ P2P transaction created: {latest_tx.get('label')}")
                        else:
                            print(f"   ⚠️  Latest transaction: {latest_tx.get('label')}")
            except Exception as e:
                print(f"   ⚠️  Could not verify transaction: {e}")
        
        # Additional verification for create_listing: check listing exists
        if test_case["expected_type"] == "create_listing":
            try:
                r = requests.get(f"{BASE_URL}/market/mine", headers=headers, timeout=10)
                if r.status_code == 200:
                    mine = r.json()
                    selling = mine.get("selling", [])
                    if len(selling) > 0:
                        print(f"   ✅ Listing appears in GET /market/mine (selling): {len(selling)} listings")
                    else:
                        print(f"   ⚠️  No listings in GET /market/mine")
            except Exception as e:
                print(f"   ⚠️  Could not verify listing: {e}")
        
        # Additional verification for launch_ad: check campaign exists
        if test_case["expected_type"] == "launch_ad":
            try:
                r = requests.get(f"{BASE_URL}/ads/campaigns", headers=headers, timeout=10)
                if r.status_code == 200:
                    campaigns = r.json()
                    if len(campaigns) > 0:
                        print(f"   ✅ Campaign appears in GET /ads/campaigns: {len(campaigns)} campaigns")
                    else:
                        print(f"   ⚠️  No campaigns in GET /ads/campaigns")
            except Exception as e:
                print(f"   ⚠️  Could not verify campaign: {e}")
        
        # ========== TEST RE-EXECUTION (should return 409) ==========
        print(f"\n[RE-EXECUTE] Testing idempotency (should return 409)...")
        try:
            r = requests.post(
                f"{BASE_URL}/ai/actions/{action_data.get('id')}/execute",
                json={"sessionId": session_id},
                headers=headers,
                timeout=15
            )
            print(f"POST /ai/actions/{action_data.get('id')}/execute (2nd time) -> {r.status_code}")
            
            if r.status_code == 409:
                print(f"✅ Re-execution correctly returned 409 (already executed)")
            else:
                print(f"❌ FAIL: Expected 409, got {r.status_code}: {r.text}")
                all_passed = False
        except Exception as e:
            print(f"❌ FAIL: Re-execute error: {e}")
            all_passed = False
        
        current_balance = after_balance
    
    # ========== TEST ERROR CASES ==========
    print(f"\n{'=' * 80}")
    print("TEST 5: Error Cases")
    print(f"{'=' * 80}")
    
    # Test 401: No Bearer token
    print("\n[ERROR] Testing 401 (no Bearer token)...")
    try:
        r = requests.post(f"{BASE_URL}/ai/chat", json={"text": "test"}, timeout=10)
        print(f"POST /ai/chat (no auth) -> {r.status_code}")
        if r.status_code == 401:
            print(f"✅ Correctly returned 401")
        else:
            print(f"❌ FAIL: Expected 401, got {r.status_code}")
            all_passed = False
    except Exception as e:
        print(f"❌ FAIL: Error test failed: {e}")
        all_passed = False
    
    # Test 400: Empty text
    print("\n[ERROR] Testing 400 (empty text)...")
    try:
        r = requests.post(f"{BASE_URL}/ai/chat", json={"text": ""}, headers=headers, timeout=10)
        print(f"POST /ai/chat (empty text) -> {r.status_code}")
        if r.status_code == 400:
            print(f"✅ Correctly returned 400")
        else:
            print(f"❌ FAIL: Expected 400, got {r.status_code}")
            all_passed = False
    except Exception as e:
        print(f"❌ FAIL: Error test failed: {e}")
        all_passed = False
    
    # Test 404: Unknown action ID
    print("\n[ERROR] Testing 404 (unknown action ID)...")
    try:
        r = requests.post(
            f"{BASE_URL}/ai/actions/nonexistent-action-id/execute",
            json={"sessionId": session_id},
            headers=headers,
            timeout=10
        )
        print(f"POST /ai/actions/nonexistent-action-id/execute -> {r.status_code}")
        if r.status_code == 404:
            print(f"✅ Correctly returned 404")
        else:
            print(f"❌ FAIL: Expected 404, got {r.status_code}")
            all_passed = False
    except Exception as e:
        print(f"❌ FAIL: Error test failed: {e}")
        all_passed = False
    
    # ========== SUMMARY ==========
    print(f"\n{'=' * 80}")
    print("PHASE 11 RE-TEST SUMMARY")
    print(f"{'=' * 80}")
    
    if all_passed:
        print("✅ ALL TESTS PASSED")
        print("\nKey findings:")
        print("- Parser robustness fix working correctly")
        print("- All 4 action types generated with correct normalized payloads")
        print("- All actions executed successfully with correct side effects")
        print("- Wallet mutations verified for money actions")
        print("- Idempotency working (409 on re-execution)")
        print("- Error handling correct (401, 400, 404)")
        return True
    else:
        print("❌ SOME TESTS FAILED")
        print("\nPlease review the detailed output above.")
        return False

if __name__ == "__main__":
    success = test_phase11_retest()
    sys.exit(0 if success else 1)
