"""Interfaces de persistance (ports). Les use-cases dépendent d'elles, jamais de SQLAlchemy."""
from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class PostRepository(Protocol):
    async def add(self, post) -> None: ...
    async def get(self, post_id: str): ...
    async def list_recent_by_authors(self, author_ids: list[str], limit: int = 30,
                                      before=None) -> list: ...


@runtime_checkable
class EdgeRepository(Protocol):
    async def add(self, edge) -> None: ...
    async def exists(self, src: str, dst: str, kind: str) -> bool: ...
    async def kinds_between(self, a: str, b: str) -> set[str]: ...
    async def following_ids(self, user_id: str) -> list[str]: ...
    async def blocked_ids(self, user_id: str) -> set[str]: ...


@runtime_checkable
class UnitOfWork(Protocol):
    posts: PostRepository
    edges: EdgeRepository

    async def __aenter__(self) -> "UnitOfWork": ...
    async def __aexit__(self, *exc) -> None: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...
